spring:
  application:
    name: healthcare-service
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: mihealthservice@gmail.com
    password: 'tiwr spfc yfsn jjfj'    # App Name: myHealthApi at https://myaccount.google.com/apppasswords
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: '/api-docs'
    enabled: true